title: Course name (is in _config.yml)

description: > # this means to ignore newlines until "contact:"
  Course description.

contact:
  email: firstname.lastname@uit.no
  name: Firstname Lastname

url: "http://uit-inf-XXX-Y20YY.github.io/"

# you don't need to adapt the settings below
baseurl: ""
markdown: kramdown
